### ISSUE TITLE
Allow test with opencv and subsystems from desktop

### ISSUE THREAD

**Issue by Marius-Juston** [wpilibsuite/vscode-wpilib#205]
We have a test folder and we are trying to test opencv functionlities in java to verify that everything is working as intended; however, when trying to run the test it informed me of a
```
java.io.IOException: ntcorejni could not be loaded from path or an embedded resource.
	attempted to load for platform /windows/x86-64/
```
 
I have managed to solve that issue for just using opencv becasue no opencv class references the WPILIB library loading functionlity 
```
  private static void loadNativeLibraries() {
    Path path = Paths.get(RuntimeLoader.getDefaultExtractionRoot(), RuntimeDetector.getPlatformPath());

    File file = path.toFile();

    for (File nativeLibrary : Objects.requireNonNull(file.listFiles())) {
      System.out.printf("Loading: %s from %s%n", nativeLibrary.getName(), nativeLibrary.getAbsolutePath());
      System.load(nativeLibrary.getAbsolutePath());
    }
  }
```

Everything works with just opencv now; however, trying to included subsystems it trys to load the "ntcorejni" library and tries to load it from the incorrect locations.
I have tried changing the java.library.path or the -Djava.library.path to be equal to PATH_TO_PROJECT\DeepSpaceRobot\build\tmp\jniExtractDir and now it gives me a 
`
java.lang.UnsatisfiedLinkError: Can't find dependent libraries`

Also is it possible to include after deployment test as to check things like if motors are plugged in and working?

**Comment by ThadHouse** [comment]
Are you trying to use the run and debug buttons over every tests? Those don't work, and as you could tell, it's not easy to get them working. Part of the issue is how windows does libraries, the jniExtractDir actually needs to be the working directory of the program as well. 

Your tests do run when you use the build or run commands we provide.

As for after deployment, that's more what test mode on the ds is for.
