### ISSUE TITLE
C++ Include Errors and Go to Definition Not Working

### ISSUE THREAD

**Issue by Kython89** [wpilibsuite/vscode-wpilib#344]
Most includes have a red squiggle under them.  Ctrl + Clicking or right clicking "Go to Definition" doesn't work.

Refreshing Intellisense has no affect.

Restarting VSCode rectifies the problem.

I know this came up during the beta but the steps to reproduce aren't obvious.  As the season has started and we have been working more we are running to this a lot.

This happens on Windows and Mac

**Comment by elisPogace** [comment]
This has been a known issue since for as long as WPI has used VS Code. (https://docs.wpilib.org/en/latest/docs/software/wpilib-overview/known-issues.html#c-intellisense-files-open-on-launch-don-t-work-properly)

You can find a hacky solution here: https://github.com/elisPogace/missingVSCodeIncludes

I'm testing a long term fix and it should be ready by the start of next week.

**Comment by Kython89** [comment]
Okay.  Thanks for working on a long term fix.  

After reading the known issue you linked I can recall the underlying problem....I just forgot over the break :(
