### ISSUE TITLE
Upgrade to VS Code 1.50.1 to Address Security Concern

### ISSUE THREAD

**Issue by travisjweber** [wpilibsuite/vscode-wpilib#392]
What is the best way to upgrade the version of VS Code we're using on our developer machines? I'm not seeing a way to use another install or upgrade an existing FRC VS Code instance.

Here is the security advisory recommending upgrade to version 1.50.1:
https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-17023

**Comment by ThadHouse** [comment]
It looks like that bug was actually started around 1.49, so the version shipped in the installer should still be safe.

But, if you do want to update, just click the gear in the bottom left of VS Code, and click check for updates. That will force an update check to occur. Note there might be bugs in the VS Code wpilib extension if you do this, we don't explicitly every version (Although I know many people do, so it should be fine).

**Comment by travisjweber** [comment]
Thanks for the quick reply!! After changing my update mode to manual I was able to see the check for updates option and download the latest, I'll have to test it out to see if there are any issues.
