### ISSUE TITLE
JAVA HOME needs to be set

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/vscode-wpilib#53]
We should look into if there is a better way to configure vs code to use a specific jdk.

**Comment by ThadHouse** [comment]
This isn't something we can reliably do from our VS Code extension. This is something that needs to be fixed upstream.

**Comment by ThadHouse** [comment]
https://github.com/redhat-developer/vscode-java/issues/599

Here's the issue I created, and the code is easy enough to PR a fix.

Basically we want VS Codes search order to match gradlew's

**Comment by sciencewhiz** [comment]
It looks like you can set it in the settings. https://stackoverflow.com/questions/42340927/java-programming-with-microsoft-visual-studio-code

**Comment by ThadHouse** [comment]
Yes it can be set there, but I don't know if I'm comfortable forcibly settings other plugins settings. I'll have to think. I would rather just upstream gets fixed. I'll PR that.

**Comment by kennethkau** [comment]
Would it be possible to set `java.home` in `.vscode/settings.json` (workspace settings) for the project?

**Comment by ThadHouse** [comment]
Yes that is also a solution or individual teams, but one that is not easy for us to do from our side, and highly not recommended for us to automatically do from our extension.

If you're going to do that though, set it globally (Open the settings in VS Code, and place them in User Settings). Because that setting is likely different between computers, its not something you want in a workspace folder.

**Comment by ThadHouse** [comment]
This has been solved in 308d3307f8655aad9240cf10499ab3d46f205c87 so closing.
