### ISSUE TITLE
String concatenation optimization

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/vscode-wpilib#537]
Per https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8278540, a potential workaround for the string concatenation poor performance is to compile with -XDstringConcat=inline.  This should be added to the build templates for FRC.

**Comment by Starlight220** [comment]
Not sure why this issue is here and not in GradleRIO.

We add  `-Djava.lang.invoke.stringConcat=BC_SB` here:
https://github.com/wpilibsuite/GradleRIO/blob/main/src/main/java/edu/wpi/first/gradlerio/deploy/roborio/FRCJavaArtifact.java#L40
Do we want to replace, have both, some conditional, something else?

And I presume that `-XDstringConcat=inline` would need to be in the compiler args and not in the JVM args?

**Comment by ThadHouse** [comment]
That argument does nothing as of Java 14. So we need to find some other replacement.

**Comment by Starlight220** [comment]
You're referring to `BC_SB` that does nothing in recent JDKs? Or `inline`?

**Comment by ThadHouse** [comment]
Bc_sb

**Comment by Starlight220** [comment]
Would the aforementioned compiler option be a proper replacement?

**Comment by PeterJohnson** [comment]
I didn’t open the issue on GR because the templates live in this repo.

**Comment by Starlight220** [comment]
Why to the template and not in GR itself?

**Comment by PeterJohnson** [comment]
So teams can choose to change it if they so choose.  I guess if there's a way to override it, it doesn't need to be.
