### ISSUE TITLE
WPILib Extensions in VS Code Marketplace Outdated

### ISSUE THREAD

**Issue by tails618** [wpilibsuite/vscode-wpilib#638]
The extension listed in the VS Code marketplace [here](https://marketplace.visualstudio.com/items?itemName=wpilibsuite.vscode-wpilib) is outdated and hasn't been updated since January 2022, but there is no indication of that in the listing of the extension; the wording should be changed so teams do not think that is what they need to install.

**Comment by lazychino** [comment]
+1, This should be updated for anyone using custom setup.

**Comment by ThadHouse** [comment]
I'll see if we can change the readme to point to the wpilib installer. We don't plan on keeping the vscode on the marketplace up to date. Our only supported method is the installer. We only put it on the marketplace to squat on the name and to stop anyone else from uploading it.

**Comment by garrettsummerfi3ld** [comment]
Some of this may not touch the subject of this extension but I do think it fits here.

Would it make sense for already existing installations to use a existing VS Code profile? The installer points to using an already existing ZIP for VS Code. Plus, since WPILib 2024 is going to be jumping from v1.74 to v1.84 we gain [profile support](https://code.visualstudio.com/docs/editor/profiles).

Exporting a basic, but "pre-canned" profile would be huge for cutting down multiple installs of VS Code. Having two entirely separate versions of VS Code to jump through is a pain since I have all my preferences on one installation but the extension and other key functions exist only on that other install. Another downside is some extensions that require logins will just break at times. Switching instances causes extensions to "forget" credentials on both instances. Installing the extension locally can fix this, but syncing all of the special configurations for it from the install can be daunting. Having the WPILib installer spit out an exported profile with the extension somewhere and loaded into a currently installed VS Code is going to be easier for offline installations.

As far as not updating the marketplace extension, I don't know if that is wise as [GitHub Codespaces](https://github.com/features/codespaces) or other remote tools such as [github.dev](https://github.dev) or [vscode.dev](https://vscode.dev) are gaining traction for those who cannot run those tools locally. Having it at _least somewhat_ available with some of the newer features that don't require offline use should be available. Underlying key functions such as deploying or running simulators and other tools won't work but the bare minimum to perform light programming work should be somewhat available with a **huge** asterisk.

**Comment by lazychino** [comment]
The projects config can be setup with [workspace settings](https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings) without needing to have a dedicated VS code for each version. I tested this on my personal machine and work nicely. 

Using profiles can make the experience even better because allows more control over the environment.

**Comment by ThadHouse** [comment]
The extension on the marketplace is now a blank extension that tells people to use the installer. The installer is our only approved solution.
